# scripts to run before build
before_build:
  - echo Running cmake...
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - mkdir build
  - cd build
#  - cmake .. -DWITH_QT5=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CD%
  - cmake .. -DWITH_QT5=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CD% -G "Visual Studio 14 2015 Win64"
  - echo CMake_defines.h...
  - type ..\include\general\CMake_defines.h
  - echo .
  
# force Release in the build
build_script:
  - cmake --build . --target INSTALL --config Release
  - cd ..
  # copy Qt DLL into bin
  - copy %QTDIR%\bin\QtCore.dll    bin
  - copy %QTDIR%\bin\QtGui.dll     bin
  - copy %QTDIR%\bin\QtXml.dll     bin
  - copy %QTDIR%\bin\QtOpenGL.dll  bin
  - copy %QTDIR%\bin\QtWidgets.dll bin
  - dir bin

after_build:
  - 7z a micmac_win.zip bin\ binaire-aux\ include\XML_MicMac\ include\XML_GEN\
  
artifacts:
  path: micmac_win.zip
  name: micmac_win

deploy:
  description: 'AppVeyor build'
  artifact: micmac_win
  auth_token:
    secure: /bJuMkK+l78lspexK/xcdi0TsITsIuiuW7nNnY8Aw1cI+k33h4epHXs2z/f6sJjJ
  provider: GitHub
  on:
    appveyor_repo_tag: true
