# scripts to run before build
before_build:
  - echo Running cmake...
  - mkdir build
  - cd build
#  - cmake .. -DWITH_QT5=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CD%
  - cmake .. -DWITH_QT5=ON -DQt5Widgets_DIR=C:\Qt\5.8\msvc2015_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%CD%

# force Release in the build
build_script:
  - cmake --build . --target INSTALL --config Release
  - cd ..

after_build:
  - 7z a micmac_win.zip bin\ binaire-aux\ include\XML_MicMac\ include\XML_GEN\
  
artifacts:
  path: micmac_win.zip
  name: micmac_win

deploy:
  description: 'AppVeyor build'
  artifact: micmac_win
  auth_token:
    secure: /bJuMkK+l78lspexK/xcdi0TsITsIuiuW7nNnY8Aw1cI+k33h4epHXs2z/f6sJjJ
  provider: GitHub
  on:
    appveyor_repo_tag: true
